Task service
SimplyMedia/MangaMagnet pull request #2
Opened 2024-01-28 18:23 UTC by GerardSmit

Adds a task service which is being updated through websockets.

https://github.com/SimplyMedia/MangaMagnet/assets/2109929/3a02f9f3-3315-4799-b425-8406e9028174

**Usage**
```cs
using var task = progressService.CreateTask("Updating manga");

for (var i = 1; i <= 100; i++)
{
	task.Progress = i;
	await Task.Delay(20);
}
```

Other stuff:

**Frontend**
- **Removed proxy**
   Websockets aren't supported by Next. I tried 3 middlewares (http-proxy, http-proxy-middleware, next-http-proxy-middleware) but none are working. So I gave up and removed it.
- **Fixed Dockerfile** 
   The public folder was removed, so the build was failing.

**Docker compose**
- Added nginx that proxies the `/api` route to the back-end.

2024-01-28 18:33 UTC, GerardSmit commented on backend/MangaMagnet.Api/Service/WebSocketService.cs
> +			await socket.SendAsync(memory, WebSocketMessageType.Text, true, stoppingToken);
1. Need to add a `try..catch` around here
2. Maybe send the message in Parallel, if some clients are slow (or being disconnected) all the other clients will get a delayed updated.

2024-01-28 18:33 UTC, GerardSmit commented on backend/MangaMagnet.Api/Service/BroadcastProgressService.cs
> +				var writer = new Utf8JsonWriter(buffer);
Need to add a `try..catch` from here til the `SendToAllAsync`, so the BackgroundService doesn't quit when a client or serializer throws an error.

2024-01-28 18:33 UTC, GerardSmit commented on backend/MangaMagnet.Api/Controller/TestController.cs
> +public class TestController(ProgressService progressService) : ControllerBase
Remove this controller after the test button is cleaned up.

2024-01-28 18:33 UTC, GerardSmit commented on frontend/src/pages/manga/[id].tsx
> +						src={manga.metadata.coverImageUrl! /* TODO: Fallback image */}
Build was failing because of a change in the model in another commit. The `src` cannot be null, so we should have a fallback URL here.

2024-01-28 18:33 UTC, GerardSmit commented on frontend/src/pages/index.tsx
> +			<button className={"m-4 p-2 bg-black"} onClick={() => TestService.testProgressTask()}>Test Task</button>
Remove this test button.

2024-01-28 18:33 UTC, GerardSmit commented on frontend/src/components/layout/Layout.tsx
> +				{tasks.length > 0 && (
It's probably better to make a component out of this.

2024-01-28 18:33 UTC, GerardSmit commented on frontend/next.config.js
> +	reactStrictMode: false, // Moved to _app.tsx, otherwise providers are called twice
Added a comment why I did this: the websocket was connecting and instantly disconnecting.
It seems like `<React.StrictMode />` is causing `useEffect(..., [])` to trigger twice.
So I disabled strict mode here and moved it to _app.tsx.

2024-01-28 18:33 UTC, GerardSmit commented on backend/MangaMagnet.Core/Progress/Models/ProgressTask.cs
> +	private string? _name = "New task";
Remove nullable.

2024-01-31 20:22 UTC, DevYukine requested changes
other than that LGTM

2024-01-31 20:22 UTC, DevYukine commented on frontend/next.config.js
> +	reactStrictMode: false, // Moved to _app.tsx, otherwise providers are called twice
This is only relevant in develop mode for react strict mode, as its not an issue in production please change this back

2024-01-31 20:22 UTC, DevYukine commented on frontend/src/pages/_app.tsx
> +	return (
As mentioned in the other comment as Strict Mode is only relevant in dev mode please change this back

2024-02-10 00:44 UTC, DevYukine approved these changes

2024-02-10 00:45 UTC, merged